### ISSUE TITLE
Compilation problem with ESPHome 2024.7.0 ?

### ISSUE THREAD

**Issue by Ben0it** [echavet/MitsubishiCN105ESPHome#134]
Since ESPHome 2024.7.0, compilation fails.

I did a clean-up of build files and tried full compilation again, without success :

![image](https://github.com/user-attachments/assets/7fa69562-9e68-4188-9001-817e1bc68303)

**Comment by Matze5800** [comment]
This is fixed now, please try again.
See [https://github.com/echavet/MitsubishiCN105ESPHome/issues/131](https://github.com/echavet/MitsubishiCN105ESPHome/issues/131)

**Comment by Ben0it** [comment]
Thanks for pointing me to this, I made the mistake of searching in open issues only.

I still have the problem despite build file cleanups from web interface. It seems the previous cn105 code is used.

Is there a more effective way of cleaning or updating the external component cache ?

Web UI cleanup results into this : 
![image](https://github.com/user-attachments/assets/0adfc4c4-3105-416e-9592-52003a1c5c14)

**Comment by Matze5800** [comment]
You could try setting the refresh time temporarily to 0s, this should force an update of the local cache.

Like this:
```
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
    refresh: 0s
```

**Comment by Ben0it** [comment]
Thank you very much for the `refresh` attribute, that did the trick :)

**Comment by Ben0it** [comment]
Thank you very much for the `refresh` attribute, that did the trick :)
