### ISSUE TITLE
Remote Control (IR) Commands overridden by wantedSettings 

### ISSUE THREAD

**Issue by echavet** [echavet/MitsubishiCN105ESPHome#2]
new wantedSettings policy, based on comparisons bt wantedSettings structure and currentSettings has a bias : if the change comes from IR remote control, the process thinks wanteSettings are not satisfied anymore and send the packet again to update the heatpump settings. As a result IR control commands are overridden and lost.
States can be inconsistant with currentSetting.
todo: detect this case and update wantedSettings.

**Comment by echavet** [comment]
Corrected in commit 950e36c5992cd4a2229d55b2e6912ad1ad734707

**Comment by echavet** [comment]
corrected on commit 950e36c5992cd4a2229d55b2e6912ad1ad734707

**Comment by jaggil** [comment]
Hi @echavet,
I have the latest version installed, but this problem persists.
My model is PKA-M50KAL2, and after the first operation with Home Assistant (HA), the remote control is locked.

In the repository at https://github.com/SwiCago/HeatPump, it mentions "enableExternalUpdate()":
"By default, the library ignores changes made from other sources (usually the IR remote) and reverts them the next time sync() is called. This is the intended behavior when the heat pump is fully controlled by automation.

If you want to also allow manual control and allow the library to update its settings from the current state of the heat pump, you need to call enableExternalUpdate(). This will also enable automatic updates."

Is there any way to enable simultaneous operation from the IR and Home Assistant?

Thanks in advance.

**Comment by echavet** [comment]
Both should work at the same time. 
But I admit I haven't test my RC for a long long time. 
I'll have a look.

**Comment by echavet** [comment]
I have tested in my home. The RC works well. But I don't have the latest firmware installed on my controlers. A few pull request have been merged yesterday. Maybe there is a regression. But I don't think so.

**Comment by jaggil** [comment]
I occasionally get these messages in the log:

18:45:38	[I]	[CYCLE:052]	6: Cycle ended in 1.1 seconds (with timeout?:  NO)
18:45:43	[I]	[CYCLE:039]	1: Cycle start
18:45:44	[I]	[CYCLE:052]	6: Cycle ended in 1.1 seconds (with timeout?:  NO)
18:45:49	[I]	[CYCLE:039]	1: Cycle start
18:46:00	[W]	[CN105:009]	Cycle timeout, resetting cycle...
18:46:00	[I]	[CYCLE:052]	**6: Cycle ended in 11.0 seconds (with timeout?: YES)**
18:46:06	[I]	[CYCLE:039]	1: Cycle start
18:46:06	[W]	[Decoder:054]	**declared data length 252 too large, resetting parser**
18:46:16	[W]	[CN105:009]	Cycle timeout, resetting cycle...
18:46:16	[I]	[CYCLE:052]	**6: Cycle ended in 11.0 seconds (with timeout?: YES)**
18:46:22	[I]	[CYCLE:039]	1: Cycle start
18:46:22	[I]	[main:721]	Remote humidity received from HA: 40.6 C
18:46:23	[I]	[CYCLE:052]	6: Cycle ended in 1.1 seconds (with timeout?:  NO)
18:46:28	[I]	[CYCLE:039]	1: Cycle start
.....
18:47:29	[I]	[CYCLE:039]	1: Cycle start
18:47:30	[W]	[CYCLE:089]	Soft timeout for Power/Standby (0x09), failures: 1
18:47:30	[W]	[chkSum:094]	**KO-> B1!=00** 
18:47:32	[I]	[main:721]	Remote humidity received from HA: 40.6 C
18:47:40	[W]	[CN105:009]	Cycle timeout, resetting cycle...
18:47:40	[I]	[CYCLE:052]	**6: Cycle ended in 11.0 seconds (with timeout?: YES)**
18:47:45	[I]	[CYCLE:039]	1: Cycle start
....
19:01:13	[I]	[main:721]	Remote humidity received from HA: 41.1 C
19:01:20	[W]	[CN105:009]	Cycle timeout, resetting cycle...
19:01:21	[I]	[CYCLE:052]	**6: Cycle ended in 11.0 seconds (with timeout?: YES)**
19:01:26	[I]	[CYCLE:039]	1: Cycle start
19:01:26	[W]	[Decoder:054]	**declared data length 252 too large, resetting parser**
19:01:36	[W]	[CN105:009]	Cycle timeout, resetting cycle...
19:01:37	[I]	[CYCLE:052]	6: Cycle ended in 11.0 seconds (with timeout?: YES)
19:01:42	[I]	[CYCLE:039]	1: Cycle start
...
19:13:32 | [I] | [CYCLE:039] | 1: Cycle start
19:13:32 | [W] | [component:522] | **uptime.sensor took a long time for an operation (55 ms), max is 30 ms**
19:13:33 | [I] | [CYCLE:052] | 6: Cycle ended in 1.1 seconds (with timeout?:  NO)
19:13:34 | [I] | [main:721] | Remote humidity received from HA: 41.5 C

Could this be related to the IR problem?
The CN105 controller is installed on an ESP8266.
